export const REGIONS = {
  zhangjiang: { name: '张江', slug: 'zhangjiang' },
  jinqiao: { name: '金桥', slug: 'jinqiao' },
  tangzhen: { name: '唐镇', slug: 'tangzhen' },
  chuansha: { name: '川沙', slug: 'chuansha' },
  changning: { name: '长宁', slug: 'changning' },
};

export const REGION_NAMES = {
  anshan: '鞍山',
  anting: '安亭',
  baihe: '白鹤',
  baozhen: '堡镇',
  beicai: '北蔡',
  beiwaitan: '北外滩',
  beixinjing: '北新泾',
  biyun: '碧云',
  buyecheng: '不夜城',
  caohejing: '漕河泾',
  caojiadu: '曹家渡',
  caolu: '曹路',
  caoyang: '曹杨',
  changfeng1: '长风',
  changqiao: '长桥',
  changshoulu: '长寿路',
  changxingdao21211: '长兴岛',
  changzheng: '长征',
  chedun: '车墩',
  chenjiazhen: '陈家镇',
  chonggu: '重固',
  chongmingqita: '崇明其它',
  chongmingxincheng: '崇明新城',
  chuansha: '川沙',
  chunshen: '春申',
  dachangzhen: '大场镇',
  dahua: '大华',
  daning: '大宁',
  dapuqiao: '打浦桥',
  datuanzhen: '大团镇',
  dongjiadu: '董家渡',
  dongjing2: '洞泾',
  dongwaitan: '东外滩',
  fengcheng: '奉城',
  fengxianjinhui: '奉贤金汇',
  fengzhuang: '丰庄',
  ganquanyichuan: '甘泉宜川',
  gaodong: '高东',
  gaohang: '高行',
  gaojing: '高境',
  geqing: '合庆',
  gongfu: '共富',
  gongkang: '共康',
  guangxin: '光新',
  gubei: '古北',
  gucun: '顾村',
  gumei: '古美',
  haiwan: '海湾',
  hanghua: '航华',
  hangtou: '航头',
  hengshadao: '横沙岛',
  hengshanlu: '衡山路',
  hongqiao1: '虹桥',
  huacao: '华漕',
  huadongligong: '华东理工',
  huaihaizhonglu: '淮海中路',
  huajing: '华泾',
  huamu: '花木',
  huangpubinjiang: '黄浦滨江',
  huangxinggongyuan: '黄兴公园',
  huating: '华亭',
  huaxin: '华新',
  huinan: '惠南',
  jiadinglaocheng: '嘉定老城',
  jiadingxincheng: '嘉定新城',
  jiangninglu: '江宁路',
  jiangqiao: '江桥',
  jianguoxilu: '建国西路',
  jiangwanzhen: '江湾镇',
  jiaxing: '嘉兴',
  jingansi: '静安寺',
  jinganxincheng: '静安新城',
  jinhongqiao: '金虹桥',
  jinhui: '金汇',
  jinqiao: '金桥',
  jinshanxincheng: '金山新城',
  jinyang: '金杨',
  jinze: '金泽',
  jiuting: '九亭',
  juyuanxinqu: '菊园新区',
  kangjian: '康健',
  kangqiao: '康桥',
  kongjianglu: '控江路',
  kunshan1: '昆山',
  laogangzhen: '老港镇',
  laominhang: '老闵行',
  laoximen: '老西门',
  liangcheng: '凉城',
  liantang1: '练塘',
  lianyang: '联洋',
  lingangxincheng: '临港新城',
  linpinglu: '临平路',
  longbai: '龙柏',
  longhua: '龙华',
  lujiazui: '陆家嘴',
  luodian: '罗店',
  luojing: '罗泾',
  luxungongyuan: '鲁迅公园',
  malu: '马陆',
  maogang: '泖港',
  maqiao: '马桥',
  meilong: '梅陇',
  meiyuan1: '梅园',
  minpu: '闵浦',
  nanjingdonglu: '南京东路',
  nanjingxilu: '南京西路',
  nanmatou: '南码头',
  nanqiao: '南桥',
  nanxiang: '南翔',
  nichengzhen: '泥城镇',
  penglaigongyuan: '蓬莱公园',
  pengpu: '彭浦',
  pujiang1: '浦江',
  qibao: '七宝',
  qidong1: '启东',
  qingcun: '青村',
  quyang: '曲阳',
  renminguangchang: '人民广场',
  sanlin: '三林',
  shangda: '上大',
  shanghainanzhan: '上海南站',
  shanghaizhoubian2: '上海周边',
  sheshan: '佘山',
  shibo: '世博',
  shibobinjiang: '世博滨江',
  shihudang: '石湖荡',
  shuyuanzhen: '书院镇',
  sichuanbeilu: '四川北路',
  sijing: '泗泾',
  situan: '四团',
  songbao: '淞宝',
  songjiangdaxuecheng: '松江大学城',
  songjianglaocheng: '松江老城',
  songjiangxincheng: '松江新城',
  songnan: '淞南',
  suhewan: '苏河湾',
  taicang212: '太仓',
  tangqiao: '塘桥',
  tangzhen: '唐镇',
  taopu: '桃浦',
  tianlin: '田林',
  tianshan: '天山',
  tonghe: '通河',
  waigang: '外冈',
  waigaoqiao: '外高桥',
  wanli: '万里',
  wantiguan: '万体馆',
  wanxiangzhen: '万祥镇',
  weifang: '潍坊',
  wujiaochang: '五角场',
  wujing: '吴泾',
  wuliqiao: '五里桥',
  wuning: '武宁',
  xianghuaqiao: '香花桥',
  xianxia: '仙霞',
  xiaokunshan: '小昆山',
  xiayang: '夏阳',
  xidu: '西渡',
  xietulu: '斜土路',
  xijiao: '西郊',
  xinbang: '新浜',
  xinchang: '新场',
  xinchenglu1: '新成路',
  xinhualu: '新华路',
  xinjiangwancheng: '新江湾城',
  xinminbieshu: '莘闵别墅',
  xinqiao: '新桥',
  xintiandi: '新天地',
  xinzhuangbeiguangchang: '莘庄北广场',
  xinzhuangnanguangchang: '莘庄南广场',
  xizangbeilu: '西藏北路',
  xuanqiao: '宣桥',
  xuhuibinjiang: '徐汇滨江',
  xujiahui: '徐家汇',
  xujing: '徐泾',
  xuxing: '徐行',
  yangcheng: '阳城',
  yangdong: '杨东',
  yanghang: '杨行',
  yangjing: '洋泾',
  yangsiqiantan: '杨思前滩',
  yexie: '叶榭',
  yingpu: '盈浦',
  yonghe: '永和',
  yuanshen: '源深',
  yuepu: '月浦',
  yuqiao1: '御桥',
  yuyuan: '豫园',
  zhabeigongyuan: '闸北公园',
  zhangjiang: '张江',
  zhangmiao: '张庙',
  zhaoxiang: '赵巷',
  zhelin: '柘林',
  zhenguang: '真光',
  zhenninglu: '镇宁路',
  zhenru: '真如',
  zhiwuyuan: '植物园',
  zhongshangongyuan: '中山公园',
  zhongyuan1: '中原',
  zhongyuanliangwancheng: '中远两湾城',
  zhoujiazuilu: '周家嘴路',
  zhoupu: '周浦',
  zhuanghang: '庄行',
  zhuanqiao: '颛桥',
  zhujiajiao: '朱家角',
  zhuqiao: '祝桥',
};

export const WORKPLACES = [
  { key: 'shanghai_tower', name: '上海中心大厦', lat: 31.2335, lng: 121.5054, address: '浦东新区陆家嘴' },
  { key: 'swfc', name: '上海环球金融中心', lat: 31.2343, lng: 121.5078, address: '浦东新区陆家嘴' },
  { key: 'ifc_sh', name: '上海国金中心', lat: 31.2364, lng: 121.5022, address: '浦东新区陆家嘴' },
  { key: 'henglong', name: '上海恒隆广场', lat: 31.2277, lng: 121.4536, address: '静安区南京西路' },
  { key: 'wheelock', name: '上海会德丰国际广场', lat: 31.2216, lng: 121.4448, address: '静安区南京西路' },
  { key: 'bfc', name: '上海BFC外滩金融中心', lat: 31.2267, lng: 121.4979, address: '黄浦区外滩' },
  { key: 'century_finance', name: '上海陆家嘴世纪金融广场', lat: 31.2128, lng: 121.5353, address: '浦东新区陆家嘴' },
  { key: 'zhangjiang_gate', name: '上海张江科学之门', lat: 31.1865, lng: 121.6175, address: '浦东新区张江' },
  { key: 'chuangzhi', name: '上海创智天地', lat: 31.3060, lng: 121.5123, address: '杨浦区五角场' },
  { key: 'caohojing', name: '上海漕河泾科技绿洲', lat: 31.1661, lng: 121.3904, address: '闵行区漕河泾' },
];

export const DISTANCE_RINGS = [3, 5, 8, 10, 15];

export const RING_COLORS = {
  3: '#2ecc71',
  5: '#27ae60',
  8: '#f39c12',
  10: '#e67e22',
  15: '#e74c3c',
};

export const RING_LABELS = {
  3: '0-3km 步行可达',
  5: '3-5km 骑行/短途',
  8: '5-8km 短途公交',
  10: '8-10km 公交',
  15: '10-15km 需地铁',
};

export const REGION_COLORS = {
  zhangjiang: '#4e79a7',
  jinqiao: '#f28e2b',
  tangzhen: '#e15759',
  chuansha: '#76b7b2',
  changning: '#59a14f',
};

// ============================================================
// 北京配置
// ============================================================

export const BJ_REGION_NAMES = {
  andingmen: '安定门', anningzhuang1: '安宁庄', anzhen1: '安贞',
  aolinpikegongyuan11: '奥林匹克公园', baishiqiao1: '白石桥',
  baizhifang1: '白纸坊', baiziwan: '百子湾', bajiao1: '八角',
  beidadi: '北大地', beigongda: '北工大', beiguan: '北关',
  beijingnanzhan1: '北京南站', beiqijia: '北七家',
  beitaipingzhuang: '北太平庄', beiyuan2: '北苑', binhexiqu1: '滨河西区',
  caihuying: '菜户营', caoqiao: '草桥', changchunjie: '长椿街',
  changpingqita1: '昌平其它', changwa: '厂洼', changyang1: '长阳',
  changying: '常营', chaoqing: '朝青', chaoyanggongyuan: '朝阳公园',
  chaoyangmennei1: '朝阳门内', chaoyangmenwai1: '朝阳门外',
  chegongzhuang1: '车公庄', chengguan: '城关', chengshousi1: '成寿寺',
  chengzi: '城子', chongwenmen: '崇文门', dahongmen: '大红门',
  dashanzi: '大山子', dawanglu: '大望路',
  daxingjichangkonggang: '大兴机场空港', daxingqita11: '大兴其它',
  daxingxinjichang: '大兴新机场', dayu: '大峪', dengshikou: '灯市口',
  deshengmen: '德胜门', dianmen: '地安门', dingfuzhuang: '定福庄',
  dinghuisi: '定慧寺', dongba: '东坝', dongdan: '东单',
  dongdaqiao: '东大桥', dongguan: '东关', donghuashi: '东花市',
  dongsi1: '东四', dongzhimen: '东直门', doudian: '窦店',
  dougezhuang: '豆各庄', dujiakan: '杜家坎', erlizhuang: '二里庄',
  fangshanqita: '房山其它', fangzhuang1: '方庄', fatou: '垡头',
  fengcun: '冯村', fengtaiqita1: '丰台其它', fuchengmen: '阜成门',
  ganjiakou: '甘家口', ganluyuan: '甘露园', gaobeidian: '高碑店',
  gaomidian: '高米店', gongti: '工体', gongzhufen: '公主坟',
  guanganmen: '广安门', guangqumen: '广渠门', guanyinsi: '观音寺',
  guanyuan: '官园', guanzhuang: '管庄', gubei: '古北',
  gubeikouzhen: '古北口镇', gucheng: '古城', guloudajie: '鼓楼大街',
  guloujiedao: '鼓楼街道', guoyuan1: '果园', guoyuanjiedao: '果园街道',
  guozhan1: '国展', haidianbeibuxinqu1: '海淀北部新区',
  haidianqita1: '海淀其它', hancunhe1: '韩村河', hepingli: '和平里',
  heyi: '和义', hongmiao: '红庙', houshayu1: '后沙峪',
  huairouchengqu1: '怀柔', huairouqita1: '怀柔其它',
  huangcunhuochezhan: '黄村火车站', huangcunzhong: '黄村中',
  huanlegu: '欢乐谷', huaweiqiao: '华威桥', huaxiang: '花乡',
  huilongguan2: '回龙观', huixinxijie: '惠新西街', huoying: '霍营',
  jianguomennei: '建国门内', jianguomenwai: '建国门外',
  jianxiangqiao1: '健翔桥', jiaodaokou: '交道口', jiaomen: '角门',
  jinbaojie: '金宝街', jinrongjie: '金融街', jinsong: '劲松',
  jiugong1: '旧宫', jiuxianqiao: '酒仙桥', junbo1: '军博',
  kandanqiao: '看丹桥', kejiyuanqu: '科技园区', laoshan1: '老山',
  liangmaqiao: '亮马桥', liangxiang: '良乡', linheli: '临河里',
  liqiao1: '李桥', lishuiqiao1: '立水桥', liujiayao: '刘家窑',
  liulihe: '琉璃河', liuliqiao1: '六里桥', liupukang: '六铺炕',
  liyuan: '梨园', lize: '丽泽', lugouqiao1: '卢沟桥', lugu1: '鲁谷',
  luyuan: '潞苑', madian1: '马甸', majiabao: '马家堡',
  majuqiao1: '马驹桥', maliandao1: '马连道', malianwa: '马连洼',
  mapo: '马坡', mentougouqita1: '门头沟其它', miyunzhen: '密云镇',
  mudanyuan: '牡丹园', muxidi1: '木樨地', muxiyuan1: '木樨园',
  nankou: '南口', nanshao: '南邵', nanshatan1: '南沙滩',
  niujie: '牛街', nongzhanguan: '农展馆', panjiayuan1: '潘家园',
  pingguoyuan1: '苹果园', puhuangyu: '蒲黄榆', qianmen: '前门',
  qiaozhuang: '乔庄', qilizhuang: '七里庄', qinghe11: '清河',
  qingta1: '青塔', sanlitun: '三里屯', sanyuanqiao: '三元桥',
  shahe2: '沙河', shanganditie: '上岸地铁', shangdi1: '上地',
  shaoyaoju: '芍药居', shibalidian1: '十八里店', shifoying: '石佛营',
  shijicheng: '世纪城', shijingshanqita1: '石景山其它',
  shilibao: '十里堡', shilihe: '十里河', shilipuzhen: '十里堡镇',
  shimenying: '石门营', shoudoujichang1: '首都机场', shuangjing: '双井',
  shuangqiao: '双桥', shuangyushu: '双榆树', shunyicheng: '顺义城',
  shunyiqita1: '顺义其它', sihui: '四惠', sijiqing: '四季青',
  songjiazhuang: '宋家庄', suzhouqiao: '苏州桥',
  taipingqiao1: '太平桥', taiyanggong: '太阳宫',
  taoranting1: '陶然亭', tiancun1: '田村', tiangongyuan: '天宫院',
  tiangongyuannan: '天宫院南', tianningsi1: '天宁寺',
  tianshuiyuan: '甜水园', tiantan: '天坛', tiantongyuan1: '天通苑',
  tianzhu1: '天竺', tongzhoubeiyuan: '通州北苑',
  tongzhouqita11: '通州其它', tuanjiehu: '团结湖', wanda14: '万达',
  wangjing: '望京', wanliu: '万柳', wanshoulu1: '万寿路',
  wanyuan1: '万源', weigongcun: '魏公村', wudaokou: '五道口',
  wukesong1: '五棵松', wulidian: '五里店', wulituo: '五里坨',
  wuyihuayuan: '武夷花园', xiaohongmen: '小红门',
  xiaotangshan1: '小汤山', xiaoxitian1: '小西天', xibahe: '西坝河',
  xibeiwang: '西北旺', xidan: '西单', xierqi1: '西二旗',
  xiguanhuandao: '西关环岛', xihongmen: '西红门', xijiao: '西郊',
  xiluoyuan: '西罗园', xingong: '新宫', xinjiekou2: '新街口',
  xisanqi1: '西三旗', xishan21: '西山', xisi1: '西四',
  xiwengzhuangzhen: '溪翁庄镇', xizhimen1: '西直门',
  xuanwumen12: '宣武门', xueyuanlu1: '学院路', yancun: '阎村',
  yangqiao1: '洋桥', yangzhen: '杨镇', yangzhuang1: '杨庄',
  yansha1: '燕莎', yanshan: '燕山', yayuncun: '亚运村',
  yayuncunxiaoying: '亚运村小营', yiheyuan: '颐和园',
  yihezhuang: '义和庄', yinghai: '瀛海', yizhuang1: '亦庄',
  yizhuanghexiqu: '亦庄河西区', yongdingmen: '永定门',
  youanmennei11: '右安门内', youanmenwai: '右安门外',
  yuanmingyuan: '圆明园', yuegezhuang: '岳各庄', yuetan: '月坛',
  yuqiao: '玉桥', yuquanlu11: '玉泉路', yuquanying: '玉泉营',
  zaojunmiao: '皂君庙', zaoyuan: '枣园', zhaogongkou: '赵公口',
  zhaoyangqita: '朝阳其它', zhichunlu: '知春路',
  zhongguancun: '中关村', zhongyangbieshuqu1: '中央别墅区',
  zizhuqiao: '紫竹桥', zuoanmen1: '左安门',
};

export const BJ_WORKPLACES = [
  { key: 'zhongxin_tower', name: '北京中信大厦', lat: 39.9129, lng: 116.4663, address: '朝阳区CBD' },
  { key: 'guomao_iii', name: '北京国贸三期', lat: 39.9125, lng: 116.4598, address: '朝阳区国贸' },
  { key: 'zhongguanzun', name: '北京中国尊', lat: 39.9129, lng: 116.4663, address: '朝阳区CBD' },
  { key: 'yintai', name: '北京银泰中心', lat: 39.9074, lng: 116.4593, address: '朝阳区国贸' },
  { key: 'huamao', name: '北京华贸中心', lat: 39.9092, lng: 116.4808, address: '朝阳区华贸' },
  { key: 'wfc_bj', name: '北京环球金融中心', lat: 39.9187, lng: 116.4590, address: '朝阳区CBD' },
  { key: 'fortune', name: '北京财富中心', lat: 39.9161, lng: 116.4601, address: '朝阳区CBD' },
  { key: 'kerry_bj', name: '北京嘉里中心', lat: 39.9141, lng: 116.4593, address: '朝阳区国贸' },
  { key: 'yinglan', name: '北京金融街英蓝国际金融中心', lat: 39.9206, lng: 116.3579, address: '西城区金融街' },
  { key: 'rongke', name: '北京融科资讯中心', lat: 39.9835, lng: 116.3261, address: '海淀区中关村' },
];

// ============================================================
// 杭州配置
// ============================================================

export const HZ_REGION_NAMES = {
  aoti: '奥体', baimahu: '白马湖', banshan: '半山',
  binjiangquzhengfu: '滨江区政府', caihe1: '采荷',
  caihongcheng: '彩虹城', changhe: '长河', changqing1112: '长庆',
  chaohui: '朝晖', chaoming11: '潮鸣', chengdongxincheng: '城东新城',
  chengzhan: '城站', chongxian: '崇贤', daguan: '大关',
  dajiangdong: '大江东', desheng: '德胜', deshengdong: '德胜东',
  dingqiao: '丁桥', donghu6: '东湖', daxuechengbei: '大学城北',
  feicuicheng1: '翡翠城', fuxing: '复兴', gaojiaoyuanqudong: '高教园区东',
  gaojiaoyuanquxi: '高教园区西', gongchenqiao: '拱宸桥',
  gongyeyuanbei: '工业园北', gongyeyuannan: '工业园南',
  gouzhuang: '勾庄', gulou2: '鼓楼', guali: '瓜沥',
  hemu: '和睦', heping2: '和平', hubin1: '湖滨',
  huajiachi: '华家池', huochedongzhan: '火车东站', hushu1: '湖墅',
  jianguobeilu: '建国北路', jianqiao: '笕桥', jinhua2: '进化',
  jinshahu: '金沙湖', jinjiang1: '近江', jingfang1: '景芳',
  jiubao: '九堡', liangzhu: '良渚', liuxia1: '留下',
  linpingxincheng: '临平新城', linpingyunhe: '临平运河', linpu: '临浦',
  liushuiyuan: '流水苑', laoyuhang: '老余杭', nanbuwocheng: '南部卧城',
  nanxing: '南星', nanxiaobu: '南肖埠', pingyao: '瓶窑',
  puyan: '浦沿', qibao1: '七堡', qianjiangshijicheng: '钱江世纪城',
  qianjiangxincheng: '钱江新城', qiaosi: '乔司', qiaoxi1: '桥西',
  qingbo: '清波', qingtai: '清泰', renhe2: '仁和',
  sanliting: '三里亭', sandun: '三墩', santang: '三塘',
  shenhua: '申花', shiqiao: '石桥', sichoucheng1: '丝绸城',
  sijiqing1: '四季青', tangqi1: '塘栖', tiyuchanglu: '体育场路',
  tianshui1: '天水', wandaguangchang2: '万达广场', wangjiang: '望江',
  weilaikejicheng: '未来科技城', wenyan: '闻堰', xianlin1: '闲林',
  xianghu: '湘湖', xiaoheshan: '小和山', xiaoshankaifaqu: '萧山开发区',
  xiaoshankejicheng: '萧山科技城', xiaoshanshiqu: '萧山市区',
  xiaoshanxinchengqu: '萧山新城区', xihujingqu: '西湖景区',
  xingqiao: '星桥', xiongzhenlou: '雄镇楼', xixi: '西溪',
  xixing: '西兴', xinyifang: '信义坊', yanjiangbei: '沿江北',
  yanjiangnan: '沿江南', yiqiao: '义桥', yunhexincheng: '运河新城',
  zhanongkou: '闸弄口', zhonganqiao: '众安桥', zhongtai: '中泰',
  wulin11: '武林',
};

export const HZ_WORKPLACES = [
  { key: 'raffles_hz', name: '杭州来福士中心', lat: 30.2487, lng: 120.2131, address: '上城区钱江新城' },
  { key: 'pingan_hz', name: '杭州平安金融中心', lat: 30.2510, lng: 120.2130, address: '上城区钱江新城' },
  { key: 'huarun_hz', name: '杭州华润大厦', lat: 30.2538, lng: 120.2150, address: '上城区钱江新城' },
  { key: 'qianjiang_core', name: '杭州钱江新城核心区', lat: 30.2520, lng: 120.2050, address: '上城区钱江新城' },
  { key: 'efc', name: '杭州EFC欧美金融城', lat: 30.2811, lng: 120.0031, address: '余杭区未来科技城' },
  { key: 'alixixi', name: '杭州阿里西溪园区', lat: 30.2782, lng: 120.0311, address: '余杭区西溪' },
  { key: 'netease', name: '杭州网易杭州园区', lat: 30.1520, lng: 120.2017, address: '滨江区网商路' },
  { key: 'hikvision', name: '杭州海康威视总部', lat: 30.2100, lng: 120.2211, address: '滨江区阡陌路' },
  { key: 'iot_town', name: '杭州滨江物联网小镇', lat: 30.2122, lng: 120.2290, address: '滨江区物联网街' },
  { key: 'yunqi', name: '杭州云栖小镇', lat: 30.1277, lng: 120.0849, address: '西湖区云栖小镇' },
];

// ============================================================
// 深圳配置
// ============================================================

export const SZ_REGION_NAMES = {
  bagualing: '八卦岭', baihua: '百花', baishida: '百仕达',
  baishizhou: '白石洲', bantian: '坂田', baoanzhongxin: '宝安中心',
  bihai1: '碧海', bujidafen: '布吉大芬', bujiguan: '布吉关',
  bujijie: '布吉街', bujinanling: '布吉南岭', bujishiyaling: '布吉石牙岭',
  bujishuijing: '布吉水径', buxin: '布心', chegongmiao: '车公庙',
  chiwei: '赤尾', chunfenglu: '春风路', cuizhu: '翠竹',
  danzhutou: '丹竹头', daxuecheng3: '大学城', dayunxincheng: '大运新城',
  diwang: '地王', dongmen: '东门', fanshen: '翻身',
  futianbaoshuiqu: '福田保税区', futianzhongxin: '福田中心',
  fuyong: '福永', gongming: '公明', guangming1: '光明',
  guanlan: '观澜', hangcheng: '航城', henggang: '横岗',
  honghu: '洪湖', hongshan6: '红山', hongshuwan: '红树湾',
  houhai: '后海', huangbeiling: '黄贝岭', huanggang: '皇岗',
  huangmugang: '黄木岗', huaqiangbei: '华强北', huaqiangnan: '华强南',
  huaqiaocheng1: '华侨城', jingtian: '景田', kejiyuan: '科技园',
  lianhua: '莲花', liantang: '莲塘', longgangbaohe: '龙岗宝荷',
  longgangshuanglong: '龙岗双龙', longgangzhongxincheng: '龙岗中心城',
  longhuaxinqu: '龙华新区', longhuazhongxin: '龙华中心',
  luohukouan: '罗湖口岸', luoling: '螺岭', meilin: '梅林',
  meilinguan: '梅林关', meisha: '梅沙', minzhi: '民治',
  nanshanzhongxin: '南山中心', nantou: '南头', pingdi: '坪地',
  pinghu: '平湖', qianhai: '前海', qingshuihe: '清水河',
  shajing: '沙井', shangbu: '上步', shangtang: '上塘',
  shangxiasha: '上下沙', shatoujiao: '沙头角', shawei: '沙尾',
  shekou: '蛇口', shenzhenwan: '深圳湾', shixia: '石厦',
  shiyan: '石岩', songgang: '松岗', sungang: '笋岗',
  taoyuanju: '桃源居', wanxiangcheng: '万象城', xiangmeibei: '香梅北',
  xiangmihu: '香蜜湖', xicheng1: '西城', xili1: '西丽',
  xinan: '西乡', xinxiu: '新秀', xinzhou1: '新洲',
  xixiang: '西乡', yantiangang: '盐田港', yinhu: '银湖',
  yuanling: '园岭', zhuzilin: '竹子林',
};

export const SZ_WORKPLACES = [
  { key: 'pingan_sz', name: '深圳平安金融中心', lat: 22.5332, lng: 114.0556, address: '福田区福田CBD' },
  { key: 'tencent_binhai', name: '深圳腾讯滨海大厦', lat: 22.5228, lng: 113.9353, address: '南山区科技园' },
  { key: 'huarun_chunsun', name: '深圳华润春笋', lat: 22.5150, lng: 113.9465, address: '南山区后海' },
  { key: 'kexing', name: '深圳科兴科学园', lat: 22.5482, lng: 113.9436, address: '南山区科技园' },
  { key: 'shenzhenwan_eco', name: '深圳深圳湾科技生态园', lat: 22.5299, lng: 113.9525, address: '南山区科技园' },
  { key: 'tencent_tower', name: '深圳腾讯大厦', lat: 22.5404, lng: 113.9346, address: '南山区科技园' },
  { key: 'baidu_sz', name: '深圳百度国际大厦', lat: 22.5246, lng: 113.9422, address: '南山区科技园' },
  { key: 'dji', name: '深圳大疆天空之城', lat: 22.5775, lng: 113.9429, address: '南山区留仙洞' },
  { key: 'skyworth', name: '深圳创维半导体设计大厦', lat: 22.5373, lng: 113.9536, address: '南山区科技园' },
  { key: 'zhongliang', name: '深圳中粮科技园', lat: 22.5760, lng: 113.9230, address: '宝安区中粮科技创新园' },
];

// ============================================================
// 城市配置
// ============================================================

export const CITY_CONFIG = {
  shanghai: {
    name: '上海',
    workplaces: WORKPLACES,
    regionNames: REGION_NAMES,
    defaultCenter: [31.22, 121.54],
    defaultZoom: 25,
    bounds: { latMin: 30.7, latMax: 31.9, lngMin: 120.8, lngMax: 122.0 },
    dataPath: 'shanghai/',
  },
  beijing: {
    name: '北京',
    workplaces: BJ_WORKPLACES,
    regionNames: BJ_REGION_NAMES,
    defaultCenter: [39.92, 116.40],
    defaultZoom: 25,
    bounds: { latMin: 39.4, latMax: 41.1, lngMin: 115.4, lngMax: 117.6 },
    dataPath: 'beijing/',
  },
  hangzhou: {
    name: '杭州',
    workplaces: HZ_WORKPLACES,
    regionNames: HZ_REGION_NAMES,
    defaultCenter: [30.25, 120.15],
    defaultZoom: 25,
    bounds: { latMin: 29.9, latMax: 30.6, lngMin: 119.5, lngMax: 120.7 },
    dataPath: 'hangzhou/',
  },
  shenzhen: {
    name: '深圳',
    workplaces: SZ_WORKPLACES,
    regionNames: SZ_REGION_NAMES,
    defaultCenter: [22.55, 114.05],
    defaultZoom: 25,
    bounds: { latMin: 22.4, latMax: 22.9, lngMin: 113.7, lngMax: 114.7 },
    dataPath: 'shenzhen/',
  },
};

export const CITY_LIST = Object.keys(CITY_CONFIG);
