export const REGIONS = {
  zhangjiang: { name: '张江', slug: 'zhangjiang' },
  jinqiao: { name: '金桥', slug: 'jinqiao' },
  tangzhen: { name: '唐镇', slug: 'tangzhen' },
  chuansha: { name: '川沙', slug: 'chuansha' },
  changning: { name: '长宁', slug: 'changning' },
};

export const REGION_NAMES = {
  anshan: '鞍山',
  anting: '安亭',
  baihe: '白鹤',
  baozhen: '堡镇',
  beicai: '北蔡',
  beiwaitan: '北外滩',
  beixinjing: '北新泾',
  biyun: '碧云',
  buyecheng: '不夜城',
  caohejing: '漕河泾',
  caojiadu: '曹家渡',
  caolu: '曹路',
  caoyang: '曹杨',
  changfeng1: '长风',
  changqiao: '长桥',
  changshoulu: '长寿路',
  changxingdao21211: '长兴岛',
  changzheng: '长征',
  chedun: '车墩',
  chenjiazhen: '陈家镇',
  chonggu: '重固',
  chongmingqita: '崇明其它',
  chongmingxincheng: '崇明新城',
  chuansha: '川沙',
  chunshen: '春申',
  dachangzhen: '大场镇',
  dahua: '大华',
  daning: '大宁',
  dapuqiao: '打浦桥',
  datuanzhen: '大团镇',
  dongjiadu: '董家渡',
  dongjing2: '洞泾',
  dongwaitan: '东外滩',
  fengcheng: '奉城',
  fengxianjinhui: '奉贤金汇',
  fengzhuang: '丰庄',
  ganquanyichuan: '甘泉宜川',
  gaodong: '高东',
  gaohang: '高行',
  gaojing: '高境',
  geqing: '合庆',
  gongfu: '共富',
  gongkang: '共康',
  guangxin: '光新',
  gubei: '古北',
  gucun: '顾村',
  gumei: '古美',
  haiwan: '海湾',
  hanghua: '航华',
  hangtou: '航头',
  hengshadao: '横沙岛',
  hengshanlu: '衡山路',
  hongqiao1: '虹桥',
  huacao: '华漕',
  huadongligong: '华东理工',
  huaihaizhonglu: '淮海中路',
  huajing: '华泾',
  huamu: '花木',
  huangpubinjiang: '黄浦滨江',
  huangxinggongyuan: '黄兴公园',
  huating: '华亭',
  huaxin: '华新',
  huinan: '惠南',
  jiadinglaocheng: '嘉定老城',
  jiadingxincheng: '嘉定新城',
  jiangninglu: '江宁路',
  jiangqiao: '江桥',
  jianguoxilu: '建国西路',
  jiangwanzhen: '江湾镇',
  jiaxing: '嘉兴',
  jingansi: '静安寺',
  jinganxincheng: '静安新城',
  jinhongqiao: '金虹桥',
  jinhui: '金汇',
  jinqiao: '金桥',
  jinshanxincheng: '金山新城',
  jinyang: '金杨',
  jinze: '金泽',
  jiuting: '九亭',
  juyuanxinqu: '菊园新区',
  kangjian: '康健',
  kangqiao: '康桥',
  kongjianglu: '控江路',
  kunshan1: '昆山',
  laogangzhen: '老港镇',
  laominhang: '老闵行',
  laoximen: '老西门',
  liangcheng: '凉城',
  liantang1: '练塘',
  lianyang: '联洋',
  lingangxincheng: '临港新城',
  linpinglu: '临平路',
  longbai: '龙柏',
  longhua: '龙华',
  lujiazui: '陆家嘴',
  luodian: '罗店',
  luojing: '罗泾',
  luxungongyuan: '鲁迅公园',
  malu: '马陆',
  maogang: '泖港',
  maqiao: '马桥',
  meilong: '梅陇',
  meiyuan1: '梅园',
  minpu: '闵浦',
  nanjingdonglu: '南京东路',
  nanjingxilu: '南京西路',
  nanmatou: '南码头',
  nanqiao: '南桥',
  nanxiang: '南翔',
  nichengzhen: '泥城镇',
  penglaigongyuan: '蓬莱公园',
  pengpu: '彭浦',
  pujiang1: '浦江',
  qibao: '七宝',
  qidong1: '启东',
  qingcun: '青村',
  quyang: '曲阳',
  renminguangchang: '人民广场',
  sanlin: '三林',
  shangda: '上大',
  shanghainanzhan: '上海南站',
  shanghaizhoubian2: '上海周边',
  sheshan: '佘山',
  shibo: '世博',
  shibobinjiang: '世博滨江',
  shihudang: '石湖荡',
  shuyuanzhen: '书院镇',
  sichuanbeilu: '四川北路',
  sijing: '泗泾',
  situan: '四团',
  songbao: '淞宝',
  songjiangdaxuecheng: '松江大学城',
  songjianglaocheng: '松江老城',
  songjiangxincheng: '松江新城',
  songnan: '淞南',
  suhewan: '苏河湾',
  taicang212: '太仓',
  tangqiao: '塘桥',
  tangzhen: '唐镇',
  taopu: '桃浦',
  tianlin: '田林',
  tianshan: '天山',
  tonghe: '通河',
  waigang: '外冈',
  waigaoqiao: '外高桥',
  wanli: '万里',
  wantiguan: '万体馆',
  wanxiangzhen: '万祥镇',
  weifang: '潍坊',
  wujiaochang: '五角场',
  wujing: '吴泾',
  wuliqiao: '五里桥',
  wuning: '武宁',
  xianghuaqiao: '香花桥',
  xianxia: '仙霞',
  xiaokunshan: '小昆山',
  xiayang: '夏阳',
  xidu: '西渡',
  xietulu: '斜土路',
  xijiao: '西郊',
  xinbang: '新浜',
  xinchang: '新场',
  xinchenglu1: '新成路',
  xinhualu: '新华路',
  xinjiangwancheng: '新江湾城',
  xinminbieshu: '莘闵别墅',
  xinqiao: '新桥',
  xintiandi: '新天地',
  xinzhuangbeiguangchang: '莘庄北广场',
  xinzhuangnanguangchang: '莘庄南广场',
  xizangbeilu: '西藏北路',
  xuanqiao: '宣桥',
  xuhuibinjiang: '徐汇滨江',
  xujiahui: '徐家汇',
  xujing: '徐泾',
  xuxing: '徐行',
  yangcheng: '阳城',
  yangdong: '杨东',
  yanghang: '杨行',
  yangjing: '洋泾',
  yangsiqiantan: '杨思前滩',
  yexie: '叶榭',
  yingpu: '盈浦',
  yonghe: '永和',
  yuanshen: '源深',
  yuepu: '月浦',
  yuqiao1: '御桥',
  yuyuan: '豫园',
  zhabeigongyuan: '闸北公园',
  zhangjiang: '张江',
  zhangmiao: '张庙',
  zhaoxiang: '赵巷',
  zhelin: '柘林',
  zhenguang: '真光',
  zhenninglu: '镇宁路',
  zhenru: '真如',
  zhiwuyuan: '植物园',
  zhongshangongyuan: '中山公园',
  zhongyuan1: '中原',
  zhongyuanliangwancheng: '中远两湾城',
  zhoujiazuilu: '周家嘴路',
  zhoupu: '周浦',
  zhuanghang: '庄行',
  zhuanqiao: '颛桥',
  zhujiajiao: '朱家角',
  zhuqiao: '祝桥',
};

export const WORKPLACES = [
  { key: 'zhangjiang', name: '张江国创中心', lat: 31.2214, lng: 121.6282, address: '浦东新区丹桂路899号' },
  { key: 'zhangjiang_2', name: '张江国创二期', lat: 31.219406, lng: 121.627225, address: '浦东新区张江国创中心二期' },
  { key: 'jinqiao', name: '金桥开发区', lat: 31.2475, lng: 121.6282, address: '浦东新区金桥经济技术开发区' },
  { key: 'tangzhen', name: '唐镇', lat: 31.2150, lng: 121.6550, address: '浦东新区唐镇中心' },
  { key: 'chuansha', name: '川沙', lat: 31.1900, lng: 121.7000, address: '浦东新区川沙新镇' },
];

export const DISTANCE_RINGS = [3, 5, 8, 10, 15];

export const RING_COLORS = {
  3: '#2ecc71',
  5: '#27ae60',
  8: '#f39c12',
  10: '#e67e22',
  15: '#e74c3c',
};

export const RING_LABELS = {
  3: '0-3km 步行可达',
  5: '3-5km 骑行/短途',
  8: '5-8km 短途公交',
  10: '8-10km 公交',
  15: '10-15km 需地铁',
};

export const REGION_COLORS = {
  zhangjiang: '#4e79a7',
  jinqiao: '#f28e2b',
  tangzhen: '#e15759',
  chuansha: '#76b7b2',
  changning: '#59a14f',
};
